{{- if .Values.appSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-api.fullname" . }}-app
  labels:
    {{- include "demo-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  message: {{ .Values.appSecret.message | quote }}
{{- end }}
