---
# Non-secret lab defaults
lab_name: devsecops-lab
kind_cluster_name: devsecops
app_namespace: demo-dev
monitoring_namespace: monitoring
registry_host: localhost
registry_port: 5000
registry_url: "localhost:5000"
jenkins_http_port: 8081
jenkins_agent_port: 50000
kyverno_chart_version: "3.2.6"
prometheus_stack_chart_version: "65.1.0"
demo_api_image_name: demo-api
backup_retention_snapshots: 20
backup_retention_bundles: 10
backup_retention_lab: 7
