apiVersion: v1
kind: Namespace
metadata:
  name: demo-dev
  labels:
    name: demo-dev
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
